### ISSUE TITLE
chia.keva.app stop show blocks sometime nodes

### ISSUE THREAD

**Issue by josinaldobarbosa** [chia-toolkit/chia.keva.app#2]
is no longer displaying the list of nodes, previously it was displaying but the nodes had 0 BLOCK

![image](https://user-images.githubusercontent.com/8990316/118582049-182d4080-b769-11eb-855f-c181a53b0ce2.png)

**Comment by josinaldobarbosa** [comment]
![image](https://user-images.githubusercontent.com/8990316/118593196-a7dcea00-b77d-11eb-9898-402c4fd37cd5.png)

**Comment by kawww** [comment]
Thanks for checking status. This vps traffic unlimited but slow to run chia node. :>

**Comment by josinaldobarbosa** [comment]
understood
